### ISSUE TITLE
无法切换webview

### ISSUE THREAD

**Issue by EADD38AE** [huajiqaq/Hydrogen#108]
com.luajava.LuaException: Runtime error. /data/user/0/com.zhihu.hydrogen.x/files/settings.lua:319: 错误信息:WebView only can replace before System WebView init
堆栈回溯com.norman.webviewup.lib.WebViewReplaceException: WebView only can replace before System WebView init
	at com.norman.webviewup.lib.WebViewReplace.checkWebView(WebViewReplace.java:168)
	at com.norman.webviewup.lib.WebViewReplace.replace(WebViewReplace.java:114)
	at com.norman.webviewup.lib.WebViewUpgrade$1.lambda$onPrepareSuccess$0(WebViewUpgrade.java:97)
	at com.norman.webviewup.lib.WebViewUpgrade$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11)
	at com.norman.webviewup.lib.WebViewUpgrade$1.onPrepareSuccess(WebViewUpgrade.java:88)
	at com.norman.webviewup.lib.source.UpgradeSource.lambda$success$2$com-norman-webviewup-lib-source-UpgradeSource(UpgradeSource.java:81)
	at com.norman.webviewup.lib.source.UpgradeSource$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at com.norman.webviewup.lib.util.HandlerUtils.runInMainThread(HandlerUtils.java:11)
	at com.norman.webviewup.lib.source.UpgradeSource.success(UpgradeSource.java:80)
	at com.norman.webviewup.lib.source.UpgradePackageSource.onPrepare(UpgradePackageSource.java:34)
	at com.norman.webviewup.lib.source.UpgradeSource.prepare(UpgradeSource.java:62)
	at com.norman.webviewup.lib.source.UpgradeSource.prepare(UpgradeSource.java:44)
	at com.norman.webviewup.lib.WebViewUpgrade.upgrade(WebViewUpgrade.java:85)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.luajava.LuaJavaAPI.callMethod(Unknown Source:446)
	at com.luajava.LuaState._pcall(Native Method)
	at com.luajava.LuaState.pcall(Unknown Source:6)
	at com.luajava.LuaObject.call_aux(Unknown Source:86)
	at com.luajava.LuaObject.call(Unknown Source:1)
	at com.luajava.LuaInvocationHandler.invoke(Unknown Source:172)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy11.onItemClick(Unknown Source)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1273)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3315)
	at android.widget.AbsListView$3.run(AbsListView.java:4301)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7025)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)

stack traceback:
	[C]: in function 'error'
	/data/user/0/com.zhihu.hydrogen.x/files/settings.lua:319: in function </data/user/0/com.zhihu.hydrogen.x/files/settings.lua:318>
	[C]: in field 'upgrade'
	/data/user/0/com.zhihu.hydrogen.x/files/settings.lua:323: in function </data/user/0/com.zhihu.hydrogen.x/files/settings.lua:296>
	/data/user/0/com.zhihu.hydrogen.x/files/settings.lua:956: in function </data/user/0/com.zhihu.hydrogen.x/files/settings.lua:944>
![S40917-11032333](https://github.com/user-attachments/assets/8658e186-04ba-4128-a898-2bd37c1f6af8)

**Comment by huajiqaq** [comment]
请确保在webview未被初始化时开启 另外开启时报错没事 开启后重启App即可
